DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CHAT;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CONTACT (
        ID INT NOT NULL AUTO_INCREMENT
      , FIRST_NAME VARCHAR(16) NOT NULL
      , LAST_NAME VARCHAR(16) NOT NULL
      , BIRTH_DATE DATETIME
      , HOBBY_ID INT NOT NULL
      , PLACE_ID INT NOT NULL
      , CHAT_ID INT NOT NULL
      , PRIMARY KEY (ID)
      , CONSTRAINT FK_CONTACT_HOBBY FOREIGN KEY (HOBBY_ID) REFERENCES HOBBY(ID)
      , CONSTRAINT FK_CONTACT_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID)
      , CONSTRAINT FK_CONTACT_CHAT FOREIGN KEY (CHAT_ID) REFERENCES CHAT(ID)
);

CREATE TABLE HOBBY (
        ID INT NOT NULL AUTO_INCREMENT
      , TITLE VARCHAR(40) NOT NULL
      , DESCRIPTION VARCHAR(160) NOT NULL
      , PRIMARY  KEY (ID)
);

CREATE TABLE PLACE (
        ID INT NOT NULL AUTO_INCREMENT
      , TITLE VARCHAR(40) NOT NULL
      , DESCRIPTION VARCHAR(160) NOT NULL
      , LATITUDE DECIMAL(2, 2) NOT NULL
      , LONGITUDE DECIMAL (3, 2) NOT NULL
      , PRIMARY KEY (ID)
);

CREATE TABLE POST (
        ID INT NOT NULL AUTO_INCREMENT
      , CONTACT_ID INT NOT NULL
      , CONTENT VARCHAR(200)
      , DATE DATETIME NOT NULL
      , PRIMARY KEY (ID)
      , CONSTRAINT FK_POST_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID)
);

CREATE TABLE MESSAGE (
        ID INT NOT NULL AUTO_INCREMENT
      , DATE DATETIME NOT NULL
      , CONTENT VARCHAR(200)
      , PRIMARY KEY (ID)
);

Create TABLE CHAT (
        ID INT NOT NULL
      , FROM_CONTACT_ID INT NOT NULL
      , TO_CONTACT_ID INT NOT NULL
      , MESSAGE_ID INT NOT null
      , PRIMARY KEY (ID)
      , CONSTRAINT FK_CONTACT_FROM FOREIGN KEY (FROM_CONTACT_ID) REFERENCES CONTACT(ID)
      , CONSTRAINT FK_CONTACT_TO FOREIGN KEY (TO_CONTACT_ID) REFERENCES CONTACT(ID)
      , CONSTRAINT FK_CHAT_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE(ID)
);

CREATE TABLE CATEGORY (
        ID INT NOT NULL AUTO_INCREMENT
      , TITLE VARCHAR(20)
      , DESCRIPTION VARCHAR(160)
      , PRIMARY KEY (ID)
);

CREATE TABLE HOBBY_CATEGORY (
        HOBBY_ID INT NOT NULL
      , CATEGORY_ID INT NOT NULL
      , PRIMARY KEY (HOBBY_ID, CATEGORY_ID)
      , CONSTRAINT FK_HOBBY_CATEGORY_1 FOREIGN KEY (HOBBY_ID) REFERENCES HOBBY(ID) ON DELETE CASCADE
      , CONSTRAINT FK_HOBBY_CATEGORY_2 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
);

CREATE TABLE PLACE_CATEGORY (
        PLACE_ID INT NOT NULL
      , CATEGORY_ID INT NOT NULL
      , PRIMARY KEY (PLACE_ID, CATEGORY_ID)
      , CONSTRAINT FK_PLACE_CATEGORY_1 FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID) ON DELETE CASCADE
      , CONSTRAINT FK_PLACE_CATEGORY_2 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
);